---
format:
  html:
    toc: true
    toc-location: left
    toc-title: "In this session:"
editor: 
  markdown: 
    wrap: 72
---

# Week 10: Further Reading {#sec-fr10}

There's a lot of aspects of epidemiology that we just weren't able to cover in our one-hour tutorial this week. If you are interested in undersatnding more about how to perform epidemiological analyses with R, see [The Epidemiologist R Handbook by Applied Epi](https://www.epirhandbook.com/en/). 

Not only are there great tutorials on concepts you're already familiar with, such as the basics of R and data management, but it also includes the many, many types of analyses that epidemiologists can do, such as: 

- Simple statistical tests 
- Univariate and multivariate regression
- Time series and outbreak detection 
- Epidemic modelling
- Contact tracing
- Survival analysis
- GIS (Geographic Information System) mapping 
- Phylogenetic trees 

There are plenty of epidemiology-based R resources out there: [Introduction to R for Epidemiologists](https://ucb-epi-r.github.io/), [Population Health Data Science with R](https://bookdown.org/medepi/phds/index.html), [R 4 Epidemiology](https://www.r4epi.com/), [Advanced Epidemiology with R: From Zero to Hero](https://rpubs.com/derebellons/advanced_epi_R_en), and so on... 

If you're interested in understanding more about epidemiological modelling with R, particularly using compartmental models which were discussed in the BIOL90042 lecture material, have a look through the `deSolve` R package. You can read about it in comprehensive detail on the [deSolve Website](http://desolve.r-forge.r-project.org/). 
