{
  "hash": "d78bbb84a1e90baab21032c1afbbf3f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n  - naquiz\nformat:\n  html:\n    toc: true\n    toc-location: left\n    toc-title: \"In this session:\"\n---\n\n# Workshop 6: Statistics in R {#sec-workshop06}\n\nSo far in BIOL90042, we've learnt how to identify patterns in our data by examining descriptive/summary statistics (mean, median etc) and visualising it with various plot types. In this workshop, we will learn how to formally test whether these patterns are statistically significant, using R. We will start by talking about how to check the assumptions behind a statistical test, then work through various different types of tests, as well as linear regression. We'll also see how the `ggpubr` package can help us visualise many of these tests directly on a plot.\n\nPlease note that this is not a statistics subject, so this workshop will skip over most of the mathematics underlying these tests. If you're interested, a nice overview can be found in the [Learning Statistics With R ebook](https://learningstatisticswithr.com/).\n\n::: {.callout-tip title=\"Learning Objectives\"}\nAt the end of this session, learners should be able to:\n\n1.  Test for an association between two categorical variables using a chi-squared test\n2.  Compare means across two or more groups using a t-test or ANOVA\n3.  Recognise when a parametric assumption is violated and apply the appropriate non-parametric alternative (Wilcoxon rank-sum or Kruskal-Wallis test)\n4.  Calculate a correlation coefficient between two continuous variables\n5.  Visualise the results of a statistical test directly on a plot using the `ggpubr` package\n6.  Construct simple and multiple linear regression models, including correcting for a confounding variable\n:::\n\nToday, we'll use a few extra packages, which you'll need to install. These are:\n\n-   [broom](https://broom.tidymodels.org/), which turns the outputs of old, 'base R' statistical functions into tidy tibbles\n-   [tidyrstats](https://cran.r-project.org/web/packages/tidyrstats/index.html), a package created by Brendan Ansell (previous subject coordinator) to make it easier to use linear models in a tidy way\n-   [ggpubr](https://rpkgs.datanovia.com/ggpubr/), a package designed to make it easy to create types of figures common in scientific publications\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install the new packages\ninstall.packages(\"broom\")\ninstall.packages(\"tidyrstats\")\ninstall.packages(\"ggpubr\")\n```\n:::\n\n\n::: {.callout-note title=\"What do we mean by 'base R'?\"}\n'base R' refers to the core set of functions that come built into R itself, as opposed to functions from add-on packages (like `mutate()` and `ggplot()`, which come from the `dplyr` and `ggplot2` packages in the `tidyverse`) that we need to install and load ourselves. This includes functions like `mean()` or `summary()` that we have learnt in previous workshops, as well as many of the statistical tests we'll cover today.\n:::\n\nOnce you've got them installed, don't forget to load them with the `library()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load all the packages we will use\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork)\nlibrary(broom)\nlibrary(tidyrstats)\nlibrary(ggpubr)\n```\n:::\n\n\nFinally, we need to read in the mousezempic dosage data we've been working with so far this semester. As a practice exercise, have a go at doing this yourself!\n\n::: {.callout-important title=\"Practice exercise: reading in and cleaning the dosage data\"}\nRead in `data/mousezempic_dosage_data.csv` and assign it to a variable called `dosage`. While you're at it, tidy it up a little:\n\n1.  Some of the `mouse_strain` values are inconsistently formatted (i.e. they include spaces and dashes instead of nice computer-friendly names). Recode `\"CD-1\"` to `\"CD1\"`, `\"Black 6\"` to `\"Black6\"`, and `\"BALB C\"` to `\"BALBc\"`, leaving any other values unchanged. (Hint: remember the `mutate(case_when())` pattern learnt in workshop 2, see @sec-mutate)\n2.  Remove any rows with a missing (`NA`) value\n\n<details>\n\n<summary>Solution</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage <- read_delim(\"data/mousezempic_dosage_data.csv\") %>%\n  # data processing/wrangling\n  # removing spaces and dashes to be computer-friendly\n  mutate(\n    mouse_strain = case_when(\n      mouse_strain == \"CD-1\" ~ \"CD1\",\n      mouse_strain == \"Black 6\" ~ \"Black6\",\n      mouse_strain == \"BALB C\" ~ \"BALBc\",\n      .default = mouse_strain\n    )\n  ) %>%\n  # remove NA values\n  na.omit()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 344 Columns: 9\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): mouse_strain, cage_number, replicate, sex\ndbl (5): weight_lost_g, drug_dose_g, tail_length_mm, initial_weight_g, id_num\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# check our result\ndosage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 333 × 9\n   mouse_strain cage_number weight_lost_g replicate sex    drug_dose_g\n   <chr>        <chr>               <dbl> <chr>     <chr>        <dbl>\n 1 CD1          1A                   3.75 rep1      male       0.00181\n 2 CD1          1A                   3.8  rep1      female     0.00186\n 3 CD1          1A                   3.25 rep1      female     0.00195\n 4 CD1          1A                   3.45 rep1      female     0.00193\n 5 CD1          1A                   3.65 rep1      male       0.0019 \n 6 CD1          1A                   3.62 rep1      female     0.00181\n 7 CD1          1A                   4.68 rep1      male       0.00195\n 8 CD1          1A                   3.2  rep1      female     0.00182\n 9 CD1          1A                   3.8  rep1      male       0.00191\n10 CD1          1A                   4.4  rep1      male       0.00198\n# ℹ 323 more rows\n# ℹ 3 more variables: tail_length_mm <dbl>, initial_weight_g <dbl>,\n#   id_num <dbl>\n```\n\n\n:::\n:::\n\n\nWe used `case_when()` inside a `mutate()` to recode the three inconsistent `mouse_strain` values, keeping everything else unchanged with the `.default = mouse_strain` fallback, then `na.omit()` to drop any rows missing `mouse_strain` or `sex`.\n\nNotice how the tilde `~` was used to associate the new values of mouse strain with the old ones. We will see the tilde a lot in this session, where it is used to describe the relationship/association between variables in our tests.\n\n</details>\n:::\n\n## Testing associations between categorical variables\n\nThe first type of test we will cover is that of associations between categorical variables. This will allow us to answer questions such as 'is there a systematic association between mouse strain and sex in our mousezempic study?'\n\n### Chi-squared test {#sec-chisq}\n\nThe chi-squared ($\\chi^2$) test of independence compares the observed frequency of every combination of two categorical variables against the frequency we would expect if the two variables were completely unrelated (independent).\n\nIn other words it tests the following hypotheses:\n\n-   Null hypothesis ($H_0$): the two categorical variables are independent (no association)\n-   Alternate hypothesis ($H_1$): the two categorical variables are associated\n\nBefore perfomring *any* statistical test, we need to first consider the assumptions of that test and ensure our data conforms to these. The assumptions of the ($\\chi^2$) test are as follows:\n\n::: {.callout-warning title=\"Assumptions of the ($\\chi^2$) test\"}\n-   Observations are independent of one another (each mouse is only counted once, and they do not influence each other)\n-   The categories of each variable are mutually exclusive and exhaustive (every mouse falls into exactly one strain and one sex)\n-   Expected cell counts are reasonably large — a common rule of thumb is that no more than 20% of cells should have an expected count below 5. When this is violated (e.g. for small or sparse tables), use `fisher.test()` instead, which computes an exact p value.\n\nYou can generally account for these assumptions in your study design.\n\n:::\n\nIn order to conduct a ($\\chi^2$) test, the first thing we need to do is construct a contingency table, that counts up the number of observations for every combination of our two categorical variables. In workshop 3, we discussed how to do this using `pivot_wider()` (see @sec-pivot-wider), mostly as an exercise to explain how to use that function.\n\nHowever, there is an easier way, using the base R function `table()`. Note that, for base R functions, we need to access the column names with `$`, as we did in workshop 1 (see @sec-dataframes).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign it to a variable, we'll need this\n# later to do the test\nstrain_sex_table <- table(dosage$mouse_strain, dosage$sex)\n\n# view the table\nstrain_sex_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         female male\n  BALBc      34   34\n  Black6     58   61\n  CD1        73   73\n```\n\n\n:::\n:::\n\nAs we can see, the counts in every cell are comfortably **above 5**, so a ($\\chi^2$) test is appropriate here.\n\nYou may also notice that the proportion of male and female mice looks very similar across all three strains, suggesting there may be no association between strain and sex. Let's still do the ($\\chi^2$) test though, to learn how it works. We can do this using the `chisq.test()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(strain_sex_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  strain_sex_table\nX-squared = 0.048607, df = 2, p-value = 0.976\n```\n\n\n:::\n:::\n\nThe test statistic is very small (0.05) and the p value (0.98) is far greater than 0.05, so we **fail to reject the null hypothesis**.\n\nWe can therefore conclude that there is no evidence of an association between mouse strain and sex in our `dosage` data, which is consistent with sex being allocated at random with respect to strain as we would hope for a well-designed experiment.\n\n::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding! \n\n::: question\n1\\. We want to know whether mice were allocated evenly across the three experimental replicates (`replicate`), regardless of `mouse_strain`. Which line of code correctly generates the contingency table we would need to answer this?\n\n::: choices\n::: {.choice .correct-choice}\n`table(dosage$mouse_strain, dosage$replicate)`\n:::\n\n::: choice\n`table(dosage$replicate)`\n:::\n\n::: choice\n`chisq.test(dosage$mouse_strain, dosage$replicate)`\n:::\n\n::: choice\n`pivot_wider(dosage, mouse_strain, replicate)`\n:::\n:::\n:::\n\n::: question\n2\\. Suppose the contingency table above has an expected count of 3 in one of its cells. What should we do?\n\n::: choices\n::: choice\nNothing, the ($\\chi^2$) test doesn't have any assumptions about cell counts\n:::\n\n::: choice\nRemove that cell from the table before running `chisq.test()`\n:::\n\n::: {.choice .correct-choice}\nUse `fisher.test()` instead, since the ($\\chi^2$) approximation may not be reliable with such a small expected count\n:::\n\n::: choice\nIncrease the sample size of just that cell\n:::\n:::\n:::\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  `table(dosage$mouse_strain, dosage$replicate)` builds a contingency table cross-tabulating the counts of every combination of `mouse_strain` and `replicate`, which is what we need before running a ($\\chi^2$) test.\n2.  An expected cell count of 3 is below our rule-of-thumb threshold of 5, so the ($\\chi^2$)  approximation may be unreliable here. `fisher.test()` calculates an exact p value instead and doesn't rely on this large-sample approximation.\n\n</details>\n:::\n\n### Fisher's exact test {#sec-fisher-exact}\n\nSo far, our examples from the `dosage` data have had a large enough sample size that the assumptions of our ($\\chi^2$) test are met. This means we haven't had a chance to use `fisher.test()` yet, so let's create some dummy data to try it out. Imagine a small pilot experiment: 10 knockout mice and 10 wildtype mice were each given mousezempic, and we recorded whether each one responded to treatment.\n\nThese results are given in a matrix (we'll learn more about matrices in workshop 7):\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot_table <- matrix(\n  c(8, 2,\n    3, 7),\n  nrow = 2,\n  byrow = TRUE,\n  dimnames = list(\n    genotype = c(\"knockout\", \"wildtype\"),\n    response = c(\"responder\", \"non_responder\")\n  )\n)\n\npilot_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          response\ngenotype   responder non_responder\n  knockout         8             2\n  wildtype         3             7\n```\n\n\n:::\n:::\n\n\nWith only 20 mice split across four cells, several expected counts here will fall below 5, so the ($\\chi^2$) test isn't appropriate. R will actually warn us about this if we try to use it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(pilot_table)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(pilot_table): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  pilot_table\nX-squared = 3.2323, df = 1, p-value = 0.0722\n```\n\n\n:::\n:::\n\n\nInstead, we should use `fisher.test()`, which calculates an **exact** p value based on the hypergeometric distribution, rather than relying on a large-sample approximation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(pilot_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  pilot_table\np-value = 0.06978\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   0.8821175 127.0558418\nsample estimates:\nodds ratio \n  8.153063 \n```\n\n\n:::\n:::\n\n\nNotice that this one doesn't give any warnings.\n\n## Comparing means: t-test and ANOVA {#sec-compare-means}\n\nAnother very common statistical task is testing whether a continuous outcome differs between groups. For example, does `weight_lost_g` differ between male and female mice, or between mouse strains?\n\n::: {.callout-warning title=\"Assumptions of the t-test and ANOVA\"}\n-   Observations are independent of one another\n-   The outcome is approximately normally distributed **within each group** (rather than in the dataset overall). If not, use a non-parametric test like `wilcox.test()` or `kruskal.test()`\n-   The groups have approximately equal variance. If not, use Welch's correction: `t.test(var.equal = FALSE)` or `oneway.test()`\n:::\n\n### Comparing two groups: the t-test {#sec-ttest}\n\nLet's use a t-test to determine whether `weight_lost_g` differs between male and female mice.\n\nFirst, it's always a good idea to visualise the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(x = sex, y = weight_lost_g)) +\n  geom_boxplot() +\n  # set ylim to 0 so as not to magnify small differences\n  ylim(0, 6.5)\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-9-1.png){width=2000}\n:::\n:::\n\n\nLooking at the plot, it seems like there might be a slight difference, and the variances appear fairly similar\n\n\nLet's now check the normality assumption, using a QQ-plot for each group. A **QQ (quantile-quantile) plot** compares the quantiles of our data against the quantiles we would expect if the data was perfectly normally distributed. We can make a QQ-plot using `ggplot2` with `geom_qq()`, adding a reference line with `geom_qq_line()` to make it easier to judge how similar our data is to the normal distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(sample = weight_lost_g)) +\n  geom_qq() +\n  geom_qq_line() +\n  # facet because we need to check normality for each group\n  facet_wrap(~sex)\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-10-1.png){width=2000}\n:::\n:::\n\n\nIf our data were normally distributed, the points would sit neatly along the diagonal reference line.\n\nBoth groups show a distinct curve away from the straight reference line, which suggests `weight_lost_g` is not normally distributed in either group.\n\nWe can confirm this with a Shapiro-Wilk test (using `shapiro.test()`) in each group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>%\n  filter(sex == \"male\") %>%\n  # shapiro.test() needs a vector, so use pull()\n  pull(weight_lost_g) %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.92504, p-value = 1.227e-07\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(sex == \"female\") %>%\n  pull(weight_lost_g) %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.91931, p-value = 6.155e-08\n```\n\n\n:::\n:::\n\n\nBoth p values are far below 0.05, so we reject normality in both groups.\n\nThis means a t-test isn't actually valid here (we should use the non-parametric alternative `wilcox.test()` instead), but for the sake of showing you how one works in R, let's run it anyway. We can compare this to the non-parametric test in a minute.\n\nTo run a t-test in R, use the `t.test()` function, and provide it three arguments:\n\n-   A formula of the format `y ~ x` (outcome ~ grouping variable)\n-   `data`, the dataframe that contains columns `y` and `x` from the formula\n-   `var.equal = TRUE` for a Student's t-test (assuming variances are equal) or `var.equal = FALSE` for Welch's t-test (assuming variances are not equal)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  weight_lost_g ~ sex, # compare weight lost across sex\n  data = dosage, # use dosage data\n  var.equal = TRUE # student t-test\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  weight_lost_g by sex\nt = -8.5417, df = 331, p-value = 4.897e-16\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -0.8408014 -0.5260222\nsample estimates:\nmean in group female   mean in group male \n            3.862273             4.545685 \n```\n\n\n:::\n:::\n\n\nThe p value (4.90e-16) is much smaller than 0.05, suggesting (as the output says), that there is a difference in the mean amount of weight lost by female and male mice. This is not unexpected: we know that male mice weigh more to begin with, so they therefore have more weight to lose than female mice.\n\n### Comparing more than two groups: ANOVA {#sec-anova}\n\nThe t-test only compares two groups, so while we could use it to compare male vs female mice, if we want to compare `weight_lost_g` across all three mouse strains at once, we need its multi-group extension: the ANOVA (analysis of variance). Rather than comparing two means directly, ANOVA compares the variance **between** groups to the variance **within** groups, to test whether at least one group mean differs from the others.\n\nAgain, let's begin by visualising what we are about to test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(x = mouse_strain, y = weight_lost_g)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-13-1.png){width=2000}\n:::\n:::\n\n\nNote that, just like for the t-test, ANOVA assumes our continuous variable is approximately normally distributed (which we can check using a QQ-plot or Shapiro-Wilks test):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make a qq plot\nggplot(dosage, aes(sample = initial_weight_g)) +\n  geom_qq() +\n  geom_qq_line() +\n  # facet because we need to check normality for each group\n  facet_wrap(~mouse_strain)\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-14-1.png){width=2000}\n:::\n\n```{.r .cell-code}\n# shapiro-wilks test\ndosage %>%\n  filter(mouse_strain == \"BALBc\") %>%\n  # shapiro.test() needs a vector, so use pull()\n  pull(weight_lost_g) %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.98449, p-value = 0.5605\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(mouse_strain == \"Black6\") %>%\n  pull(weight_lost_g) %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.98606, p-value = 0.2605\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(mouse_strain == \"CD1\") %>%\n  pull(weight_lost_g) %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.98116, p-value = 0.04232\n```\n\n\n:::\n:::\n\n\nThis time, we're actually only violating the normality assumption for the CD1 strain (p value 0.04)! We'll compare the result to a the non-parametric Kruskal-Wallace test later, but for now let's proceed with the ANOVA:\n\nWe can perform an ANOVA in R using the `aov()` function, with the same `y ~ x` formula notation we used for the t-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(weight_lost_g ~ mouse_strain, data = dosage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = weight_lost_g ~ mouse_strain, data = dosage)\n\nTerms:\n                mouse_strain Residuals\nSum of Squares     145.19022  70.06945\nDeg. of Freedom            2       330\n\nResidual standard error: 0.4607946\nEstimated effects may be unbalanced\n```\n\n\n:::\n:::\n\nAlthough the way we use the `aov()` function is quite similar to `t.test()`, the output looks very different! We can't see a p-value anywhere. This is because, statistically, ANOVAs are a special case of a linear model (see @sec-lm) and so the output of the `aov()` function inherits some quirks from how linear models are reported in R.\n\nTo find the p-value and answer our question, we can pass this to the `summary()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(weight_lost_g ~ mouse_strain, data = dosage) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value Pr(>F)    \nmouse_strain   2 145.19   72.60   341.9 <2e-16 ***\nResiduals    330  70.07    0.21                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThe p value is extremely small, so we conclude that `weight_lost_g` differs between at least one pair of strains. This matches our observation from the boxplot above, where Black-6 mice visibly lost more weight than BALBc or CD1 mice.\n\nWe can also get a tidy version of this table with the `tidy()` function from the `broom` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(weight_lost_g ~ mouse_strain, data = dosage) %>% tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  term            df sumsq meansq statistic   p.value\n  <chr>        <dbl> <dbl>  <dbl>     <dbl>     <dbl>\n1 mouse_strain     2 145.  72.6        342.  3.74e-81\n2 Residuals      330  70.1  0.212       NA  NA       \n```\n\n\n:::\n:::\n\n\nThis could be useful if, for example, we wanted to extract the p value and use this in further R code (e.g. to label a plot).\n\n::: {.callout-tip title=\"Which pairs of groups differ?\"}\nA significant ANOVA (or Kruskal-Wallis) result only tells us that one group differs from another, but it doesn't say which pair(s). We can find this by performing what's known as a 'post-hoc pairwise test' (e.g. Tukey's HSD (honest significant difference) test):\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(weight_lost_g ~ mouse_strain, data = dosage) %>% TukeyHSD()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = weight_lost_g ~ mouse_strain, data = dosage)\n\n$mouse_strain\n                    diff        lwr        upr    p adj\nBlack6-BALBc  1.35934874  1.1944304  1.5242671 0.000000\nCD1-BALBc    -0.02692385 -0.1862005  0.1323528 0.916431\nCD1-Black6   -1.38627259 -1.5202554 -1.2522897 0.000000\n```\n\n\n:::\n:::\n\nThis shows us that there is a statistically significant difference between Black-6 and BALBc mice, as well as betwen CD-1 and Black-6 mice, but **not** between CD-1 and BALBc mice, which matches our observations in the boxplot above.\n\n:::\n\nUnlike for `t.test()`, the `aov()` function doesn't have an argument for equal variances. If your variances aren't equal, you need to instead use the `oneway.test()` function, which does have this argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noneway.test(weight_lost_g ~ mouse_strain, data = dosage, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  weight_lost_g and mouse_strain\nF = 316.5, num df = 2.00, denom df = 187.68, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Non-parametric tests {#sec-non-para}\n\nWhen a parametric assumption (i.e. normality) is badly violated, we can turn to a non-parametric alternative instead. These tests don't assume the outcome is normally distributed and instead test for differences in the ranks of the data.\n\n::: {.callout-warning title=\"Assumptions of the Wilcoxon and Kruskal-Wallis tests\"}\n-   Observations are independent of one another\n-   The outcome variable is at least ordinal (i.e. it can be meaningfully ranked)\n-   If you want to interpret the result as a difference in medians specifically (rather than just 'the distributions differ'), the groups should have similarly shaped distributions\n:::\n\nNon-parametric tests are more robust to outliers and skewed distributions than their parametric counterparts, **but** they can be somewhat less powerful to detect a true effect when the data are actually normally distributed. Therefore, you should only use them when you really need to.\n\n#### The Wilcoxon rank-sum test {#sec-wilcox}\n\nThe Wilcoxon rank-sum test (also called the Mann-Whitney test when applied on two samples, like we will do here) is the non-parametric equivalent of the t-test we covered earlier. Instead of comparing means, it tests whether one group tends to have overall higher or lower ranked values than the other.\n\nLet's revisit our comparison of `weight_lost_g` between male and female mice. We can use it by simply replacing `t.test()` with `wilcox.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(weight_lost_g ~ sex, data = dosage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  weight_lost_g by sex\nW = 6874.5, p-value = 1.813e-15\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nThe p value is again far smaller than 0.05, so both tests agree here: male and female mice differ in weight lost.\n\n#### The Kruskal-Wallis test {#sec-kruskal}\n\nThe just like the t-test, the Wilcoxon test only compares two groups. The non-parametric version of the ANOVA we ran above is called the Kruskal-Wallis test, and we can run it using the `kruskal.test()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(weight_lost_g ~ mouse_strain, data = dosage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  weight_lost_g by mouse_strain\nKruskal-Wallis chi-squared = 212.09, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding! \n\n::: question\n1\\. If you check the normality assumption for a continuous variable in two groups using a QQ plot and Shapiro-Wilk test, and find that the assumption is clearly violated in both groups, which test should you use to compare them?\n\n::: choices\n::: choice\n`t.test()`, since it's the standard test for comparing two groups\n:::\n\n::: {.choice .correct-choice}\n`wilcox.test()`, since it doesn't assume normality\n:::\n\n::: choice\n`aov()`, since it's more powerful\n:::\n\n::: choice\n`chisq.test()`, since the normality assumption is violated\n:::\n:::\n:::\n\n::: question\n2\\. You want to compare a continuous variable across three or more groups, but a QQ plot shows the data is clearly non-normal in at least one group. Which function should you use?\n\n::: choices\n::: choice\n`aov()`\n:::\n\n::: choice\n`t.test()`\n:::\n\n::: {.choice .correct-choice}\n`kruskal.test()`\n:::\n\n::: choice\n`wilcox.test()`\n:::\n:::\n:::\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  When normality is clearly violated, `wilcox.test()` (the Wilcoxon rank-sum/Mann-Whitney test) is the appropriate choice, since it doesn't rely on the normality assumption that `t.test()` requires.\n2.  `kruskal.test()` is the non-parametric equivalent of a one-way ANOVA, and is the appropriate choice when comparing three or more groups and the normality assumption is violated.\n\n</details>\n:::\n\n## Correlation between continuous variables {#sec-correlation}\n\nSo far, we have considered situations where both, or one of our variables were categorical. If both of our variables are continuous, we can measure the strength and direction of a linear relationship between them using a correlation coefficient.\n\nA correlation coefficient ranges from -1 to 1, where:\n\n-   Values close to **1** indicate a strong *positive* relationship (as one variable increases, so does the other)\n-   Values close to **-1** indicate a strong *negative* relationship (as one variable increases, the other decreases)\n-   Values close to **0** indicate little to no linear relationship\n\n::: {.callout-warning title=\"Assumptions of the Pearson correlation\"}\n-   The relationship between the two variables is linear (check with a scatterplot before you calculate r!)\n-   Both variables are continuous\n-   No extreme outliers, which can heavily distort the correlation coefficient\n-   Ideally, both variables are roughly normally distributed\n\nIf any of these are violated (e.g. the relationship is non-linear, or there are outliers), use the non-parametric Spearman correlation instead. Spearman correlation only assumes the relationship is monotonic, since it works on the ranks of the data rather than the raw values.\n:::\n\nLet's examine the correlation between `drug_dose_g` and `weight_lost_g`.\n\nFirst, check the linearity assumption with a scatterplot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(x = drug_dose_g, y = weight_lost_g)) +\n  geom_point() +\n  # add geom_smooth to compare the points to a linear\n  # line of best fit\n  geom_smooth(method = \"lm\") +\n  labs(\n    x = \"Drug dose (g)\",\n    y = \"Weight lost (g)\",\n    title = \"Correlation between drug dose and weight lost\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-22-1.png){width=2000}\n:::\n:::\n\n\nA straight line looks like a reasonable summary of this relationship, and there don't seem to be any crazy outliers, so let's go ahead and calculate the correlation coefficient. We can do this in R using `cor.test()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cor.test() takes two arguments, the x and y variables\n# remember these must be vectors: access from df with $\ncor.test(dosage$drug_dose_g, dosage$weight_lost_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  dosage$drug_dose_g and dosage$weight_lost_g\nt = 32.562, df = 331, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.8447622 0.8963550\nsample estimates:\n      cor \n0.8729789 \n```\n\n\n:::\n:::\n\n\nThe correlation coefficient (0.87) is close to 1, and the p value is far smaller than 0.05, so we have strong evidence of a **positive linear relationship** between drug dose and weight lost. In other words, mice given a higher dose of mousezempic tended to lose more weight.\n\n::: {.callout-note title=\"Pearson vs Spearman correlation\"}\n`cor.test()` calculates a **Pearson correlation** by default, which as discussed above has a number of assumptions.\n\nIf your data are not normally distributed, contain outliers, or the relationship is monotonic but not linear (e.g. curved but always increasing), a **Spearman correlation** is a better choice. You can perform one using the `method` argument of `cor.test()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(dosage$drug_dose_g, dosage$weight_lost_g, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in cor.test.default(dosage$drug_dose_g, dosage$weight_lost_g, method =\n\"spearman\"): cannot compute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  dosage$drug_dose_g and dosage$weight_lost_g\nS = 982284, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.8403902 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding!\n\n::: question\n1\\. I ran the code `cor.test(dosage$initial_weight_g, dosage$weight_lost_g)` and got a correlation coefficient of r = 0.59, with a p value below 0.05. What can I conclude?\n\n::: choices\n::: choice\nThere is no relationship between the two variables\n:::\n\n::: {.choice .correct-choice}\nThere is a moderate, statistically significant positive relationship between the two variables\n:::\n\n::: choice\nThere is a strong negative relationship between the two variables\n:::\n\n::: choice\nThe relationship is definitely non-linear\n:::\n:::\n:::\n\n::: question\n2\\. If you suspect two continuous variables have a monotonic but non-linear relationship, with a couple of outliers, which correlation method is most appropriate?\n\n::: choices\n::: choice\nPearson, since it's the default in `cor.test()`\n:::\n\n::: {.choice .correct-choice}\nSpearman, since it only assumes a monotonic relationship and is more robust to outliers\n:::\n\n::: choice\nNeither, correlation can't be calculated for non-linear relationships\n:::\n\n::: choice\nA linear model\n:::\n:::\n:::\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  A correlation coefficient of r = 0.59 indicates a moderate positive relationship (not strong, and not negative), and since the p value is below 0.05, this relationship is statistically significant.\n2.  Spearman correlation is the better choice here, since it only assumes the relationship is monotonic (rather than strictly linear) and is calculated on the ranks of the data, making it more robust to outliers.\n\n</details>\n:::\n\n## Visualising statistical tests with ggpubr {#sec-ggpubr}\n\nSo far, we've been running our tests and making our plots in two separate steps. The `ggpubr` package (which extends ggplot2) makes it easy to combine the two, by adding the result of a statistical test directly onto a plot as an annotation. This is a great way to make quick, publication-ready figures without having to manually copy test statistics and p values into a title or label.\n\n### Adding a test result to a boxplot\n\nThe `ggboxplot()` function works similarly to `ggplot() + geom_boxplot()`, but returns a plot we can layer statistical annotations onto with `stat_compare_means()`.\n\nLet's revisit our comparison of `weight_lost_g` between male and female mice, this time adding the t-test result directly onto the plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggboxplot(\n  data = dosage,\n  # unlike in the ggplot() function, x and y are\n  # supplied directly, not in aes()\n  x = \"sex\", y = \"weight_lost_g\",\n  # in ggpubr, you add jitter using the 'add' argument\n  add = \"jitter\") +\n  stat_compare_means(method = \"t.test\") +\n  labs(x = \"Sex\", y = \"Weight lost (g)\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-25-1.png){width=2000}\n:::\n:::\n\n\nThe same idea works for our three-strain comparison, using `method = \"kruskal.test\"` (or `method = \"anova\"`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggboxplot(dosage, x = \"mouse_strain\", y = \"weight_lost_g\", add = \"jitter\") +\n  stat_compare_means(method = \"kruskal.test\") +\n  labs(x = \"Mouse strain\", y = \"Weight lost (g)\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-26-1.png){width=2000}\n:::\n:::\n\n\nWe can get `ggpubr` to add pairwise comparisons too, by supplying a list of the pairs we're interested in to the `comparisons` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggboxplot(dosage, x = \"mouse_strain\", y = \"weight_lost_g\", add = \"jitter\") +\n  # get the pairwise comparisons\n  stat_compare_means(\n    comparisons = list(c(\"BALBc\", \"Black6\"), c(\"BALBc\", \"CD1\"), c(\"Black6\", \"CD1\"))) +\n  # get the overall p value and test name\n  stat_compare_means(method = \"kruskal.test\", label.y = 8) +\n  labs(x = \"Mouse strain\", y = \"Weight lost (g)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_compare_means()` with `comparisons` displays *unadjusted* p-values (no correction for multiple comparisons).\nℹ For p-values adjusted for multiple comparisons, use `geom_pwc()`, or `stat_pvalue_manual()` together with `compare_means(..., p.adjust.method = )`.\nThis message is displayed once per session.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-27-1.png){width=2000}\n:::\n:::\n\n\nThis runs a pairwise Wilcoxon test for each pair of strains we listed, adding a significance bracket for each comparison, alongside the overall Kruskal-Wallis result. Annoyingly, we have to run `stat_compare_means()` twice, because each call only adds one type of label of the plot (either the pairwise comparisons **or** the overall p value and test name), but this is the struggle that comes with using functions written by other people, sometimes the interface doesn't quite make sense!\n\n### Adding a correlation to a scatterplot\n\nSimilarly to `ggboxplot()`, `ggscatter()` is another higher-level plotting function from `ggpubr`. It creates a scatterplot that we can annotate with `stat_cor()` to show the correlation coefficient and p value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(dosage, x = \"drug_dose_g\", y = \"weight_lost_g\", add = \"reg.line\") +\n  stat_cor(method = \"pearson\") +\n  labs(x = \"Drug dose (g)\", y = \"Weight lost (g)\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-28-1.png){width=2000}\n:::\n:::\n\n\nJust like `cor.test()`, we can switch to a Spearman correlation with the `method` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(dosage, x = \"drug_dose_g\", y = \"weight_lost_g\", add = \"reg.line\") +\n  stat_cor(method = \"spearman\") +\n  labs(x = \"Drug dose (g)\", y = \"Weight lost (g)\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-29-1.png){width=2000}\n:::\n:::\n\n\n::: {.callout-note title=\"ggpubr and ggplot2\"}\nSince `ggpubr` functions return ordinary ggplot objects, you can keep layers to them, like `theme_minimal()`, `labs()` or even `facet_wrap()`. This makes `ggpubr` a nice shortcut for making plots, while still retaining the customisation abilities you learnt in workshop 4.\n:::\n\n::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding!\n\n::: question\n1\\. Which function would you add to a `ggboxplot()` to annotate it with the result of a statistical test?\n\n::: choices\n::: choice\n`stat_cor()`\n:::\n\n::: choice\n`geom_test()`\n:::\n\n::: {.choice .correct-choice}\n`stat_compare_means()`\n:::\n\n::: choice\n`labs()`\n:::\n:::\n:::\n\n::: question\n2\\. I tried running the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(dosage, aes(x = \"drug_dose_g\", y = \"weight_lost_g\", add = \"reg.line\")) +\n  stat_cor(method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! argument \"y\" is missing, with no default\n```\n\n\n:::\n:::\n\n\nBut I got an error. Why?\n\n::: choices\n::: choice\nBecause you need to add the regression line with `geom_smooth()`\n:::\n\n::: {.choice .correct-choice}\nBecause `ggpubr` plots don't use the `aes()` function\n:::\n\n::: choice\nBecause `add` is not a valid `ggplot2` aesthetic\n:::\n\n::: choice\nBecause you used the `ggscatter()` function instead of the `ggplot()` function\n:::\n:::\n:::\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  `stat_compare_means()` adds the result of a statistical test (e.g. t-test, Kruskal-Wallis, ANOVA, or pairwise comparisons) directly onto a `ggpubr` plot as an annotation. `stat_cor()` is the equivalent for annotating a correlation coefficient onto a scatterplot.\n2.  `ggscatter()` is the `ggpubr` function for creating scatterplots, and unlike the `ggplot()` function it doesn't use `aes()`, you just specify `x` and `y` directly to `ggscatter()`\n\n</details>\n:::\n\n## Linear modelling (in the tidyverse) {#sec-lm}\n\nAs you may recall from lecture 4, linear models are very useful for testing for significant associations between variables, or significant differences between groups. They have the advantage of being able to correct for the effects of other variables, and thereby remove unwanted sources of variation that could otherwise reduce our ability to discover true relationships.\n\n::: {.callout-warning title=\"Assumptions of linear regression\"}\n-   **Linearity**: the relationship between each predictor and the outcome is a straight line\n-   **Independence**: the residuals (the differences between observed and predicted values) are independent of one another\n-   **Homoscedasticity**: the residuals have roughly constant variance across the range of fitted values\n-   **Normality of residuals**: the residuals are approximately normally distributed (this matters most for small samples — with a large enough sample, the model is fairly robust to this)\n-   For multiple regression specifically: predictors shouldn't be too strongly correlated with one another (multicollinearity)\n:::\n\n### Testing differences between groups (discrete x)\n\nEarlier in this workshop (see @sec-ttest), we used an independent t-test to check whether `weight_lost_g` differs between male and female mice. A **simple linear regression** with a single, two-level categorical predictor is mathematically identical to that t-test.\n\nLet's try running one, using `lm()` to demonstrate this. Note that just like the `aov()` function, we need to pipe this into `summary()` to get a p value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(weight_lost_g ~ sex, data = dosage) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight_lost_g ~ sex, data = dosage)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.2957 -0.5957 -0.2373  0.7377  1.7543 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.86227    0.05683  67.963  < 2e-16 ***\nsexmale      0.68341    0.08001   8.542  4.9e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.73 on 331 degrees of freedom\nMultiple R-squared:  0.1806,\tAdjusted R-squared:  0.1781 \nF-statistic: 72.96 on 1 and 331 DF,  p-value: 4.897e-16\n```\n\n\n:::\n:::\n\n\nCompare the `statistic` and `p.value` for `sexmale` to the t-test we ran earlier (t = -8.54, p = 4.9e-16, using `var.equal = TRUE`) — they match exactly. The `intercept` term is the mean for the reference group (`female`, since it comes first alphabetically), and `sexmale` is the estimated *difference* between the male and female group means.\n\nThe same is true of ANOVA: `lm(y ~ group)` with a 3+ level categorical predictor gives the same F-statistic and p value as `aov(y ~ group)`.\n\n### Testing differences relative to 0 (discrete x)\n\nBut what if we don't want to compare the male vs female mice, and instead are just interested in knowing whether either sex lost a meaningful amount of weight at all? This type of model could be useful, for example, if you were doing an experiment to compare a standard cancer treatment to a new drug: you might want to see how much each of these treatments affect survival relative to the baseline.\n\nKeeping with the previous example of weight lost vs sex, if we use `lm(weight_lost_g ~ 0 + sex)` we get the mean weight lost per group as the `estimate`, and each group mean is tested against 0 rather than against the other group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(weight_lost_g ~ 0 + sex, data = dosage) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight_lost_g ~ 0 + sex, data = dosage)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.2957 -0.5957 -0.2373  0.7377  1.7543 \n\nCoefficients:\n          Estimate Std. Error t value Pr(>|t|)    \nsexfemale  3.86227    0.05683   67.96   <2e-16 ***\nsexmale    4.54568    0.05632   80.71   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.73 on 331 degrees of freedom\nMultiple R-squared:  0.9711,\tAdjusted R-squared:  0.971 \nF-statistic:  5567 on 2 and 331 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBoth p values are very significant (because average weight lost is nowhere near 0 g in either group). However, it is important to note that we cannot conclude from this whether male and female mice differ *from each other*: that comparison requires the `weight_lost_g ~ sex` model we used above.\n\n### Testing associations between variables (continuous x)\n\nOf course, `lm_test()` works just as well for a continuous predictor. Earlier we used `cor.test()` to test the association between `drug_dose_g` and `weight_lost_g` (see the scatter plot with fitted line above), and a simple linear regression tests the same relationship, while additionally estimating a slope and intercept:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(weight_lost_g ~ drug_dose_g, data = dosage) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight_lost_g ~ drug_dose_g, data = dosage)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.05733 -0.25979 -0.01224  0.24297  1.29389 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -5.8721     0.3103  -18.93   <2e-16 ***\ndrug_dose_g 5015.3266   154.0231   32.56   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3933 on 331 degrees of freedom\nMultiple R-squared:  0.7621,\tAdjusted R-squared:  0.7614 \nF-statistic:  1060 on 1 and 331 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe p value matches the significance we saw from `cor.test()`, and the (very large) slope tells us that weight lost increases steeply with drug dose. The slope is high because `drug_dose_g` is measured in tiny fractions of a gram, so a one-unit increase in dose is an enormous increase in practice.\n\n### Making linear modelling tidy\nSimilarly to how the `tidy()` function from the `broom` package can be used to create tidy versions of the statistical tests we've covered throughout this workshop, the `lm_test()` function from the `tidyrstats` package can be used to make linear modelling tidy. This is helpful if you then want to go on to do additional calculations with the results, for example to create a `ggplot2` visualisation.\n\nAnother advantage is that because `data` is the first argument of `lm_test()`, we can pipe data into it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndose_model <- dosage %>%\n  lm_test(weight_lost_g ~ drug_dose_g)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nResults for linear model: weight_lost_g ~ drug_dose_g\n```\n\n\n:::\n\n```{.r .cell-code}\ndose_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 drug_dose_g  5015.     154.         32.6 3.13e-105\n2 intercept      -5.87     0.310     -18.9 1.18e- 54\n```\n\n\n:::\n:::\n\n\nWe can visualise this tidy fitted model with a scatterplot and a line of best fit:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pull out the intercept, slope and p value from the tidy model output\nmodel_intercept <- dose_model %>%\n  filter(term == \"intercept\") %>%\n  pull(estimate)\n\nmodel_slope <- dose_model %>%\n  filter(term == \"drug_dose_g\") %>%\n  pull(estimate)\n\nmodel_pvalue <- dose_model %>%\n  filter(term == \"drug_dose_g\") %>%\n  pull(p.value)\n\nggplot(dosage, aes(x = drug_dose_g, y = weight_lost_g)) +\n  geom_point() +\n  # draw the fitted line using the intercept/slope estimated by lm_test()\n  geom_abline(intercept = model_intercept, slope = model_slope, colour = \"blue\") +\n  # add the p value as a text label in the top-left corner of the plot\n  annotate(\n    \"text\",\n    x = -Inf, y = Inf, # hack to put in top-left corner\n    hjust = -0.1, vjust = 2,\n    # format.pval is a base R function to format p values\n    # in a nice human readable way\n    label = paste0(\"p = \", format.pval(model_pvalue, digits = 3))\n  ) +\n  labs(\n    x = \"Drug dose (g)\",\n    y = \"Weight lost (g)\",\n    title = \"Relationship between drug dose and weight lost\"\n  )\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-35-1.png){width=2000}\n:::\n:::\n\n\nYou might be wondering why we would do this rather than simply using `geom_smooth()` or `ggscatter()`, as we have already done in this workshop. It's important to understand that these functions fit their own model as part of the plotting, between the x and y variables on your plot. For the simple model we have just fitted between drug dosage and weight loss, it doesn't matter, because the models made by `geom_smooth()` and `ggscatter()` are identical to the one we've done with `lm()`, but as your models become more complex, the `lm_test()` approach becomes necessary to visualise your actual model on a scatterplot.\n\n### Correcting for covariates\n\nSo far we have tested relationships between a independent (x) and a dependent (y) variable.\n\nOften we want to ensure that other possible sources of variation are minimised so that we can better detect true differences in our 'main effect of interest'. Say we want to understand whether drug dose affects weight lost *regardless of mouse strain*. In other words, we want to subtract the mean effect of any strain-specific differences.\n\nWe already saw in our ANOVA and Kruskal-Wallis tests earlier that `weight_lost_g` differs noticeably between strains (Black6 mice lose more weight on average). Therefore, mouse strain is a plausible confounder of the drug dose/weight lost relationship.\n\nTo test the dose effect while correcting for strain, we can add `mouse_strain` to the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>%\n  lm_test(weight_lost_g ~ drug_dose_g + mouse_strain)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nResults for linear model: weight_lost_g ~ drug_dose_g + mouse_strain\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term               estimate std.error statistic  p.value\n  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>\n1 drug_dose_g        4061.     308.         13.2  3.64e-32\n2 intercept            -4.22     0.605      -6.98 1.68e-11\n3 mouse_strainBlack6    0.490    0.0870      5.63 3.84e- 8\n4 mouse_strainCD1       0.205    0.0576      3.57 4.14e- 4\n```\n\n\n:::\n:::\n\n\nThe estimated slope for `drug_dose_g` drops from about 5015 (t ≈ 32.6) in the uncorrected model above, to about 4061 (t ≈ 13.2) once we adjust for strain — some of the raw dose/weight-lost association was indeed attributable to strain differences. Even so, the p value for `drug_dose_g` remains far below 0.05, so drug dose seems to have a genuine effect on weight lost that is only *partly* explained by strain.\n\n::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding. A code-based version of this exercise (investigating `drug_dose_g`, `tail_length_mm` and Simpson's paradox) is in the practice questions at the end of the chapter, if you'd like some more hands-on practice.\n\n::: question\n1\\. You run `lm(weight_lost_g ~ drug_dose_g, data = dosage) %>% summary()` and get the following coefficients table:\n\n```\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)\n(Intercept)     0.052      0.031    1.68    0.094\ndrug_dose_g  5015.230    153.870   32.60   <2e-16 ***\n```\n\nWhat is the equation of the fitted regression line?\n\n::: choices\n::: {.choice .correct-choice}\n`weight_lost_g = 0.052 + 5015.230 * drug_dose_g`\n:::\n\n::: choice\n`weight_lost_g = 5015.230 + 0.052 * drug_dose_g`\n:::\n\n::: choice\n`weight_lost_g = 32.60 * drug_dose_g`\n:::\n\n::: choice\n`weight_lost_g = 0.094 + 5015.230 * drug_dose_g`\n:::\n:::\n:::\n\n::: question\n2\\. Why might you want to add `mouse_strain` as a covariate when modelling the relationship between `drug_dose_g` and `tail_length_mm`?\n\n::: choices\n::: choice\nTo make the p value smaller\n:::\n\n::: {.choice .correct-choice}\nTo account for `mouse_strain` as a potential confounder, so we can isolate the effect of `drug_dose_g` on its own\n:::\n\n::: choice\nIt's not necessary, `mouse_strain` has no relationship to either variable\n:::\n\n::: choice\nTo calculate a correlation coefficient\n:::\n:::\n:::\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  A simple linear regression follows the format `y = intercept + slope * x`. Here, the `(Intercept)` row gives us the intercept (0.052) and the `drug_dose_g` row gives us the slope for that predictor (5015.230), so the fitted line is `weight_lost_g = 0.052 + 5015.230 * drug_dose_g`. The `t value` and `Pr(>|t|)` columns are used to test whether each coefficient is significantly different from 0, not to build the equation itself.\n2.  We add `mouse_strain` as a covariate to account for it as a potential confounder — this lets us isolate the effect of `drug_dose_g` on `tail_length_mm` that isn't attributable to strain differences.\n\n</details>\n:::\n\nEvery model in this chapter has had a **continuous** outcome (y), such as amount of weight lost. But what if the outcome we care about is binary, for example did a mouse respond to treatment or not? In the further reading (see @sec-logistic-regression), we cover how **logistic regression** extends what we've covered here to binary outcomes.\n\n### The role of linear modelling in bioinformatics\nEverything we've covered today is the basic statistical foundation for the more advanced bioinformatics techniques we'll learn in upcoming workshops. A differential expression analysis, for example, fits exactly the same kind of linear model we've built today, just repeated across thousands of outcomes at once (individual genes, proteins or metabolites), while correcting for confounders like batch effects, and handling data that's rarely as well-behaved as ours (requiring extra filtering, transformation, and care around mean-variance relationships). Doing this at scale is a computationally demanding task, which is why R packages such as limma and edgeR, bundle the expression data, sample/gene metadata and model design together into a single specialised object, then fit all of the models and generate thousands of results in one command. We'll learn about this workflow in upcoming workshops.\n\nLinear modelling is also foundational to machine learning, which focuses on trying to use the coefficients from a fitted model, combined with the predict() function, to make predictions about new data. We'll explore machine learning in more detail in our final workshop.\n\n## Summary\n\nToday, we've covered a lot of statistical ground! Here's a quick summary of what we've learnt:\n\n-   How to check the assumptions behind a statistical test, using QQ plots and the Shapiro-Wilk test to check normality, and a scatterplot to check linearity\n-   How to test for an association between two categorical variables using `chisq.test()` (or `fisher.test()` for small/sparse tables)\n-   How to compare means with a **t-test** (two groups) or **ANOVA** (three or more groups), and the assumptions (normality within groups, equal variance) that underpin them\n-   How to choose a **non-parametric** alternative such as `wilcox.test()` or `kruskal.test()` when those assumptions are violated\n-   How to calculate and visualise a **correlation coefficient** between two continuous variables with `cor.test()`, and the difference between Pearson and Spearman correlation\n-   How to use the `ggpubr` package to add statistical test results directly onto a boxplot or scatterplot, for quick, publication-ready figures\n-   How to perform a simple linear regression with both categorical and continuous predictors\n-   How to build a **multiple linear regression** model to correct for confounders, and how this can reveal a true underlying relationship\n-   Why linear modelling at the scale used in bioinformatics (e.g. differential expression analysis) requires specialised tools like the Bioconductor packages limma and edgeR\n\nIf you'd like to learn more, check out the further reading for this week, which covers logistic regression (extending everything we've done today to a binary outcome) along with a few other topics worth knowing about. Or check out the [Learning Statistics With R ebook](https://learningstatisticswithr.com/) to cover more of the maths behind the tests we've learnt today.\n\nYou might also find this summary sheet helpful:\n\n{{< downloadthis resources/session_6_summary_sheet.pdf dname=\"session_6_summary_sheet\" label=\"Download the summary sheet for workshop 6\" icon=\"file-earmark-arrow-down\" type=\"primary\" class=\"data-button\" id=\"summarysheet\" >}}\n\n### Practice questions\n\nTry these practice questions to test your understanding! Each one revisits a question we asked earlier in the chapter, but this time you'll need to write and run the code yourself.\n\n1.  Were mice allocated evenly across the three experimental replicates (`replicate`), regardless of `mouse_strain` ?\n\n    a.  Build a contingency table of `mouse_strain` and `replicate`.\n    b.  Check your assumptions (i.e. expected cell counts).\n    c.  Run the appropriate test and state your conclusion in plain language: is there evidence of an association between strain and replicate?\n    d.  Bonus: also visualise this as a bar chart. Is your plot consistent with the result of the test?\n\n2.  Does a mouse's starting weight (`initial_weight_g`) differ by sex? And does tail length (`tail_length_mm`) differ by strain? For each question, first check your assumptions, and then use an appropriate statistical test.\n\n3.  Do heavier mice (at the start of the study) tend to lose more weight? And is there a relationship between a mouse's tail length and its starting weight? Visualise the relationship between the variables with a scatterplot to check the assumptions of Pearson correlation, and then perform an appropriate correlation calculation using `cor.test()`. Comment in words on each correlation.\n\n4.  Recreate your Kruskal-Wallis comparison of `tail_length_mm` across mouse strains (from question 2) as a `ggpubr` **violin** plot, with both the overall test result **and** pairwise comparisons annotated on the plot. Hint: try `ggviolin()` instead of `ggboxplot()`.\n\n5.  Investigate whether `drug_dose_g` predicts `tail_length_mm`, and whether `mouse_strain` confounds that relationship. Hint: pay close attention to the sign of the slope at each step, this is a bit tricky!\n\n    a.  Fit a linear model of drug dose (x) and tail length (y). Don't add covariates yet. Note the direction (sign) of the slope for `drug_dose_g`.\n    b.  Compute the mean `drug_dose_g` and mean `tail_length_mm` for each `mouse_strain` (hint: use the `summarise()` function from workshop 3). What do you notice about Black6 mice?\n    c.  Now fit the linear model with mouse strain as a covariate. What happens to the sign of the `drug_dose_g` slope compared to step (a)? Why might correcting for a confounder actually **reverse** the direction of an effect, not just weaken it?\n\n<details>\n\n<summary>Solutions</summary>\n\n1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrain_replicate_table <- table(dosage$mouse_strain, dosage$replicate)\nstrain_replicate_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         rep1 rep2 rep3\n  BALBc    26   18   24\n  Black6   33   45   41\n  CD1      44   50   52\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(strain_replicate_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  strain_replicate_table\nX-squared = 3.2711, df = 4, p-value = 0.5135\n```\n\n\n:::\n:::\n\n\nExpected counts are comfortably above 5 in every cell, so the chi-squared approximation is valid. The p value (0.51) is well above 0.05, so there is no evidence of an association between strain and replicate.\n\nFor the bonus question, you can use `geom_bar()` as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>%\n  ggplot(aes(x = mouse_strain, fill = replicate)) +\n  # position = \"fill\" creates a stacked bar chart where the\n  # number of mice in each replicate are depicted as a proportion\n  # of the total mice for each strain. If you remove this, it\n  # will just be a normal stacked bar chart where the height of\n  # the bars represents count\n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-38-1.png){width=2000}\n:::\n:::\n\n\n2.  Does a mouse's starting weight (`initial_weight_g`) differ by sex?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use QQ plot to check normality\nggplot(dosage, aes(sample = initial_weight_g)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~sex)\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-39-1.png){width=2000}\n:::\n\n```{.r .cell-code}\n# QQ plot doesn't look great, check shapiro-wilk test\ndosage %>%\n  filter(sex == \"male\") %>%\n  pull() %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.95626, p-value = 4.194e-05\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(sex == \"female\") %>%\n  pull() %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.95519, p-value = 3.925e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n# both p < 0.05: normality assumption is violated\n# need to use non-parametric test (wilcox)\nwilcox.test(initial_weight_g ~ sex, data = dosage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  initial_weight_g by sex\nW = 8178, p-value = 9.901e-11\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n`initial_weight_g` is non-normal in both groups (Shapiro-Wilk p value \\< 0.001), so a Wilcoxon test is the best choice. It shows a statistically significant difference: males are heavier.\n\nDoes tail length (`tail_length_mm`) differ by strain?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use QQ plot to check normality\nggplot(dosage, aes(sample = tail_length_mm)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~mouse_strain)\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-40-1.png){width=2000}\n:::\n\n```{.r .cell-code}\n# QQ plot looks so-so, check shapiro-wilk test\ndosage %>%\n  filter(mouse_strain == \"Black6\") %>%\n  pull() %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.95692, p-value = 0.0007659\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(mouse_strain == \"CD1\") %>%\n  pull() %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.95872, p-value = 0.0002326\n```\n\n\n:::\n\n```{.r .cell-code}\ndosage %>%\n  filter(mouse_strain == \"BALBc\") %>%\n  pull() %>%\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  .\nW = 0.95505, p-value = 0.01544\n```\n\n\n:::\n\n```{.r .cell-code}\n# all <0.05, normality is violated. use kruskal wallace test\nkruskal.test(tail_length_mm ~ mouse_strain, data = dosage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  tail_length_mm by mouse_strain\nKruskal-Wallis chi-squared = 217.56, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nTail length is non-normal, so the non-parametric Kruskal-Wallis test should be used. There is a statistically significant difference (Kruskal-Wallis p \\< 0.001) in tail length between mouse strains.\n\n3.  Do heavier mice (at the start of the study) tend to lose more weight?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(x = initial_weight_g, y = weight_lost_g)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-41-1.png){width=2000}\n:::\n\n```{.r .cell-code}\ncor.test(dosage$initial_weight_g, dosage$weight_lost_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  dosage$initial_weight_g and dosage$weight_lost_g\nt = 13.276, df = 331, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5145745 0.6554058\nsample estimates:\n      cor \n0.5894511 \n```\n\n\n:::\n:::\n\n\n`initial_weight_g` and `weight_lost_g` are moderately positively correlated (r ≈ 0.59, p \\< 0.001), so heavier mice tended to lose more weight.\n\nIs there a relationship between a mouse's tail length and its starting weight?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dosage, aes(x = tail_length_mm, y = initial_weight_g)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-42-1.png){width=2000}\n:::\n\n```{.r .cell-code}\ncor.test(dosage$tail_length_mm, dosage$initial_weight_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  dosage$tail_length_mm and dosage$initial_weight_g\nt = -4.2726, df = 331, p-value = 2.528e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.3280409 -0.1242017\nsample estimates:\n       cor \n-0.2286256 \n```\n\n\n:::\n:::\n\n\n`tail_length_mm` and `initial_weight_g` are weakly negatively correlated (r ≈ -0.23, p \\< 0.001), so mice with longer tails tend to weigh more.\n\n4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggviolin(dosage, x = \"mouse_strain\", y = \"tail_length_mm\", add = \"jitter\") +\n  stat_compare_means(\n    comparisons = list(c(\"BALBc\", \"Black6\"), c(\"BALBc\", \"CD1\"), c(\"Black6\", \"CD1\"))) +\n  # get the overall p value and test name\n  stat_compare_means(method = \"kruskal.test\", label.y = 9) +\n  labs(x = \"Mouse strain\", y = \"Tail length (mm)\")\n```\n\n::: {.cell-output-display}\n![](workshop_6_files/figure-html/unnamed-chunk-43-1.png){width=2000}\n:::\n:::\n\n\n5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>% lm_test(tail_length_mm ~ drug_dose_g)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nResults for linear model: tail_length_mm ~ drug_dose_g\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 intercept       33.5      1.27      26.4 2.51e-83\n2 drug_dose_g  -8118.     630.       -12.9 4.78e-31\n```\n\n\n:::\n:::\n\n\nThe slope is -8188 indicating as drug dose increases, tail length decreases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>% summarise(\n  mean_dose = mean(drug_dose_g),\n  mean_tail_len = mean(tail_length_mm),\n  .by = mouse_strain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  mouse_strain mean_dose mean_tail_len\n  <chr>            <dbl>         <dbl>\n1 CD1            0.00190          18.3\n2 Black6         0.00217          15.0\n3 BALBc          0.00196          18.4\n```\n\n\n:::\n:::\n\n\nWe notice that Black-6 mice have (on average) higher drug dosages and shorter tails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndosage %>% lm_test(tail_length_mm ~ drug_dose_g + mouse_strain)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nResults for linear model: tail_length_mm ~ drug_dose_g + mouse_strain\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term               estimate std.error statistic  p.value\n  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>\n1 mouse_strainBlack6   -5.20      0.228    -22.8  1.42e-69\n2 drug_dose_g        8288.      808.        10.3  1.36e-21\n3 mouse_strainCD1       0.401     0.151      2.65 8.37e- 3\n4 intercept             2.19      1.59       1.38 1.68e- 1\n```\n\n\n:::\n:::\n\n\nWe can now see that the slope is 8288: it has changed sign from negative to positive.\n\nThis is a good example of **Simpson's paradox**: the uncorrected slope for `drug_dose_g` is strongly negative (higher dose associated with shorter tails), but Black6 mice happen to have both a higher average dose and much shorter tails than the other strains. Once `mouse_strain` is added to the model, the `drug_dose_g` slope flips to strongly positive. That is, within any given strain, higher doses are actually associated with longer tails. **The uncorrected relationship was driven entirely by strain differences**, not a true dose effect in the opposite direction. We saw a similar flip in workshop 4, when adding colour to a scatterplot changed our interpretation of the relationship between initial weight and tail length (see @sec-workshop04).\n\n</details>\n",
    "supporting": [
      "workshop_6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}